contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://mingrammer.com/go-codelab"
title = "Go codelab step-by-step page"
canonifyurls = true
languageCode = "en-us"
pygmentsstyle = "monokai"
PygmentsCodeFences = true
pygmentsuseclasses = true

[permalinks]
    post = "/:filename"
