contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://mingrammer.com/go-codelab"
title = "Go codelab step-by-step page"
canonifyurls = true
languageCode = "en-us"

[permalinks]
    post = "/:filename"
